#include "FuckWindows.hpp"

std::map<int, std::wstring> FuckWindows::aaa = {
    {5, L"一\nOne\nイチ\nイツ\n\nひと\nーーーー\n八\nEight\nハチ\n\nや\nやっ\nーーーー\n人\nPerson\nジン\nニン\n\nひと\nーーーー\n二\nTwo\nニ\n\nふた\nーーーー\n入\nEnter\nニュウ\n\nい\nはい\nーーーー\n十\nTen\nジュウ\nジッ\n\nと\nとお\nーーーー\n七\nSeven\nシチ\n\nなな\nーーーー\n九\nNine\nキュウ\nク\n\nここの\nーーーー\n小\nLittle\nショウ\n\nお\nこ\nちい\nーーーー\n上\nAbove\nジョウ\n\nあ\nうえ\nかみ\nのぼ\nーーーー\n下\nBelow\nカ\nゲ\n\nお\nくだ\nさ\nした\nしも\nもと\nーーーー\n川\nRiver\nセン\n\nかわ\nーーーー\n三\nThree\nサン\n\nみ\nみっ\nーーーー\n山\nMountain\nサン\n\nやま\nーーーー\n口\nMouth\nコウ\nク\n\nくち\nーーーー\n土\nSoil\nド\nト\n\nつち\nーーーー\n千\nThousand\nセン\n\nち\nーーーー\n大\nLarge\nダイ\nタイ\n\nおお\nーーーー\n子\nChild\nシ\nス\n\nこ\nーーーー\n万\nTen thousand\nマン\nバン\n\nーーーー\n女\nWoman\nジョ\nニョ\n\nおんな\nめ\nーーーー\n六\nSix\nロク\n\nむ\nむっ\nーーーー\n少\nFew\nショウ\n\nすく\nすこ\nーーーー\n火\nFire\nカ\n\nひ\nーーーー\n父\nFather\nフ\n\nちち\nーーーー\n今\nNow\nコン\nキン\n\nいま\nーーーー\n水\nWater\nスイ\n\nみず\nーーーー\n午\nNoon\nゴ\n\nーーーー\n分\nPart\nブン\nブ\nフン\n\nわ\nーーーー\n手\nHand\nシュ\n\nて\nーーーー\n天\nHeavens\nテン\n\nあめ\nーーーー\n日\nDay\nニチ\nジツ\n\nか\nひ\nーーーー\n木\nTree\nボク\nモク\n\nき\nーーーー\n中\nIn\nチュウ\n\nなか\nーーーー\n月\nMonth\nゲツ\nガツ\n\nつき\nーーーー\n五\nFive\nゴ\n\nいつ\nーーーー\n友\nFriend\nユウ\n\nとも\nーーーー\n円\nCircle\nエン\n\nまる\nーーーー\n立\nStand up\nリツ\n\nた\nーーーー\n北\nNorth\nホク\n\nきた\nーーーー\n半\nHalf\nハン\n\nなか\nーーーー\n外\nOutside\nガイ\nゲ\n\nそと\nはず\nほか\nーーーー\n右\nRight\nウ\nユウ\n\nみぎ\nーーーー\n出\nExit\nシュツ\n\nだ\nで\nーーーー\n古\nOld\nコ\n\nふる\nーーーー\n生\nLife\nセイ\nショウ\n\nい\nう\nお\nき\nなま\nは\nーーーー\n左\nLeft\nサ\n\nひだり\nーーーー\n四\nFour\nシ\n\nよ\nよっ\nよん\nーーーー\n本\nBook\nホン\n\nもと\nーーーー\n白\nWhite\nハク\nビャク\n\nしろ\nーーーー\n目\nEye\nモク\n\nめ\nーーーー\n母\nMama\nボ\n\nはは\nーーーー\n行\nGoing\nコウ\nギョウ\n\nい\nおこな\nゆ\nーーーー\n多\nMany\nタ\n\nおお\nーーーー\n名\nName\nメイ\nミョウ\n\nな\nーーーー\n年\nYear\nネン\n\nとし\nーーーー\n会\nMeeting\nカイ\nエ\n\nあ\nーーーー\n先\nBefore\nセン\n\nさき\nーーーー\n耳\nEar\nジ\n\nみみ\nーーーー\n百\nHundred\nヒャク\n\nーーーー\n気\nSpirit\nキ\nケ\n\nーーーー\n休\nRest\nキュウ\n\nやす\nーーーー\n安\nRelax\nアン\n\nやす\nーーーー\n西\nWest\nセイ\nサイ\n\nにし\nーーーー\n毎\nEvery\nマイ\n\nーーーー\n言\nSay\nゲン\nゴン\n\nい\nこと\nーーーー\n足\nLeg\nソク\n\nあし\nた\nーーーー\n社\nCompany\nシャ\n\nやしろ\nーーーー\n花\nFlower\nカ\n\nはな\nーーーー\n何\nWhat\nカ\n\nなに\nーーーー\n来\nCome\nライ\n\nきた\nく\nーーーー\n見\nSee\nケン\n\nみ\nーーーー\n車\nCar\nシャ\n\nくるま\nーーーー\n男\nMale\nダン\nナン\n\nおとこ\nーーーー\n学\nStudy\nガク\n\nまな\nーーーー\n空\nEmpty\nクウ\n\nあ\nから\nす\nそら\nーーーー\n店\nStore\nテン\n\nみせ\nーーーー\n金\nGold\nキン\nコン\n\nかね\nーーーー\n雨\nRain\nウ\n\nあめ\nーーーー\n長\nLong\nチョウ\n\nなが\nーーーー\n東\nEast\nトウ\n\nひがし\nーーーー\n国\nCountry\nコク\n\nくに\nーーーー\n食\nEat\nショク\n\nく\nた\nーーーー\n前\nIn front\nゼン\n\nまえ\nーーーー\n後\nBehind\nゴ\nコウ\n\nあと\nうし\nおく\nのち\nーーーー\n南\nSouth\nナン\n\nみなみ\nーーーー\n校\nSchool\nコウ\n\nーーーー\n時\nTime\nジ\n\nとき\nーーーー\n高\nTall\nコウ\n\nたか\nーーーー\n書\nWrite\nショ\n\nか\nーーーー\n魚\nFish\nギョ\n\nうお\nさかな\nーーーー\n週\nWeek\nシュウ\n\nーーーー\n飲\nDrink\nイン\n\nの\nーーーー\n道\nRoad-way\nドウ\n\nみち\nーーーー\n買\nBuy\nバイ\n\nか\nーーーー\n間\nInterval\nカン\nケン\n\nあいだ\nま\nーーーー\n話\nTale\nワ\n\nはな\nはなし\nーーーー\n新\nNew\nシン\n\nあたら\nあら\nにい\nーーーー\n電\nElectricity\nデン\n\nーーーー\n読\nRead\nドク\nトク\n\nよ\nーーーー\n語\nWord\nゴ\n\nかた\nーーーー\n駅\nStation\nエキ\n\nーーーー\n聞\nHear\nブン\nモン\n\nき\nーーーー\n#\n"}
    //{5, L"一\nOne\nイチ\nイツ\n\nひと\nーーーー\n八\nEight\nハチ\n\nや\nやっ\nーーーー\n人\nPerson\nジン\nニン\n\nひと\nーーーー\n二\nTwo\nニ\n\nふた\nーーーー\n入\nEnter\nニュウ\n\nい\nはい\nーーーー\n十\nTen\nジュウ\nジッ\n\nと\nとお\nーーーー\n七\nSeven\nシチ\n\nなな\nーーーー\n九\nNine\nキュウ\nク\n\nここの\nーーーー\n小\nLittle\nショウ\n\nお\nこ\nちい\nーーーー\n#\n"}
};

std::map<int,std::wstring> FuckWindows::bbb = {
    {5, L"十一月\nじゅういちがつ\nNovember\nーーーー\n十一\nじゅういち\nEleven\nーーーー\n一生\nいっしょう\nWhole life\nーーーー\n一つ\nひとつ\nOne thing\nーーーー\n十八\nじゅうはち\nEighteen\nーーーー\n八月\nはちがつ\nAugust\nーーーー\n八十\nはちじゅう\nEighty\nーーーー\n百八\nひゃくはち\nOne hundred and eight\nーーーー\n#"}
};

